### ISSUE TITLE
Add pmod pinout to readme

### ISSUE THREAD

**Issue by terrabite3** [apfelaudio/eurorack-pmod#29]
Hello, 

I'm having trouble finding the pinout for the pmod connector. That is, which of the pins is used for which signals. If it's documented I haven't found it yet. I'm sure I could determine it by opening the schematic or reverse engineering one of the board files. But I feel that this is basic information that anyone using a different board will want to know, so it should be clearly documented somewhere obvious like the readme. 

To go above and beyond, it would be great to have an annotated photo or diagram to make it totally clear which pin is which. But that's not necessary, a clear text description would be sufficient.

**Comment by schnommus** [comment]
Hey there @terrabite3 -

Easiest place to find the pinout is on the silkscreen on the back side of the board. It looks like this:

![Screenshot_select-area_20230518073338](https://github.com/apfelaudio/eurorack-pmod/assets/1386830/fd0a968e-f6ff-477d-9f00-618c3f423018)

I agree that there should be a better description of these signals in the README.

Here is a more verbose summary of each pin, I will add this to the README:

1. SDI (AK4619VN SDIN1)
2. SCL (I2C SCL for AK4619VN CODEC, EEPROM, LED + JACK IO expanders)
3. SDO (AK4619VN SDOUT1)
4. SDA (I2C SDA)
5. LRCK (CODEC clock line)
6. PDN (CODEC power down, also connected to LED output enable and JACK reset line -- HIGH means everything is on)
7. BICK (CODEC clock line)
8. MCLK (CODEC clock line)
9. GND
10. GND
11. 3V3 IN
12. 3V3 IN

As for the assignments per-board, there are some gotchas for different FPGA boards - in some cases I have left comments in the pin assignment files for each board under gateware/boards

**Comment by terrabite3** [comment]
Hi @schnommus,

Yep, the silkscreen on the back is perfectly clear. I just hadn't received mine yet so I didn't know about it!

Your description is pretty good, but it's ambiguous which row is which. It looks like the I2C is on the top row and the I2S is on the top and bottom? The GND and 3V3 make the other dimension clear.

I'll be using an Arty A7-35T, mostly because I already have one. I'm looking forward to turning this thing on.

**Comment by schnommus** [comment]
Forgot to close this -- added the info to README. Thanks for the feedback!

You can identify pin 1 (I2S SDI) as it is the square pad, whereas the rest are round.
